
version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  build:
    commands:
      - echo Build completed successfully
      - java -jar /codebuild/output/<service-role-ARN>/build-output/your-app.jar

artifacts:
  files:
    - <path-to-folder>/**/*
    - appspec.yml
